### ISSUE TITLE
Allow selection of path

### ISSUE THREAD

**Issue by fresnik** [roboticsound/Pulsarr#27] opened 2017-09-12 22:02 UTC
As a user who categorizes my movies based on content rating I would like to be able to select the destination directory path of the selected movie in a similar fashion as CouchPotato so that different movies are put into different libraries.

**Comment by roboticsound** [comment] 2017-09-16 18:17
I will also close this issue as it is a duplicate of #13. Please continue the discussion over there.

**Closed by roboticsound** 2017-09-16 18:17 UTC
Labels: duplicate, enhancement
